/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#dfe3e9',
        'on-tertiary-container': '#828486',
        'outline-variant': '#c6c6cd',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#dce2f7',
        'on-secondary-fixed-variant': '#43474c',
        'on-primary-fixed-variant': '#404758',
        error: '#ba1a1a',
        'surface-tint': '#575e70',
        primary: '#000000',
        'primary-fixed-dim': '#c0c6db',
        'surface-container-low': '#f0f3ff',
        surface: '#f9f9ff',
        'on-secondary': '#ffffff',
        'surface-variant': '#dce2f3',
        'on-tertiary-fixed': '#191c1e',
        'surface-container-highest': '#dce2f3',
        'on-primary-container': '#7d8497',
        'on-error': '#ffffff',
        background: '#f9f9ff',
        secondary: '#5a5f64',
        'on-secondary-fixed': '#171c20',
        'surface-bright': '#f9f9ff',
        'secondary-fixed-dim': '#c3c7cd',
        'on-background': '#151c27',
        'surface-dim': '#d3daea',
        'primary-container': '#141b2b',
        'on-primary-fixed': '#141b2b',
        'on-error-container': '#93000a',
        'surface-container-high': '#e2e8f8',
        'on-surface': '#151c27',
        'tertiary-fixed-dim': '#c5c6c8',
        'on-primary': '#ffffff',
        'tertiary-container': '#191c1e',
        'surface-container': '#e7eefe',
        'tertiary-fixed': '#e1e2e4',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#ebf1ff',
        'secondary-fixed': '#dfe3e9',
        outline: '#76777d',
        tertiary: '#000000',
        'inverse-primary': '#c0c6db',
        'on-surface-variant': '#45464c',
        'on-secondary-container': '#60656a',
        'inverse-surface': '#2a313d',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#444749',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap': '64px',
        'container-padding': '24px',
        unit: '4px',
        'stack-lg': '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
        gutter: '16px',
      },
      fontFamily: {
        'display-lg': ['EB Garamond', 'serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        'display-lg-mobile': ['EB Garamond', 'serif'],
        'headline-sm': ['EB Garamond', 'serif'],
        'price-display': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'price-display': ['20px', { lineHeight: '24px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
